### PR TITLE
fix: disable tooltips while reordering items

### LINKED ISSUE #886: Really hard to reorder icons.  They jump about!
Hi,

there seems to be a random effect whereby when trying to move the icons around, clicking on one icon causes a different one to jump around, displacing previously (tediously) ordered icons.  To make life more difficult, when a new icon is added, it arrives in an unpredictable location.

Suggestion: why not provide an option to sort icons by title?  Then by simply preceding the title with a number, the desired order could be obtained easily.  Sadly, my programming skills are not adequate to contribute anything but suggestions!

### PR DESCRIPTION
**Pull request by keriati**
When we reorder the items, the tool-tips are still in the DOM with opacity set to 0. As the tool-tips are part of the item they are still clickable even when invisible and are overlapping items from the row above them. This leads to problems when people want to drag and drop them.

fixes #886

### CODE REVIEW

File: public/js/app.js [hunk 1]
```diff
@@ -641,7 +641,7 @@ $.when($.ready).then(function () {
     }
   });
   $('#sortable').sortable('disable');
-  $('#sortable').on('mouseenter', '.item', function () {
+  $(document).on('mouseenter', '#sortable.ui-sortable-disabled .item', function () {
```
Comment (keriati) [inline public/js/app.js:644]: Only trigger this when sorting is not active.

File: public/js/app.js [hunk 2]
```diff
@@ -696,8 +696,10 @@ $.when($.ready).then(function () {
       $('.add-item').hide();
       $('.item-edit').hide();
       $('#app').removeClass('sidebar');
+      $('#sortable .tooltip').css('display', '')
       $('#sortable').sortable('disable');
     } else {
+      $('#sortable .tooltip').css('display', 'none')
```
Comment (keriati) [inline public/js/app.js:702]: Display none is my safest bet here...
